std_msgs/Header header
uint8 online

float32 right_joystick_x
float32 right_joystick_y
float32 left_joystick_x
float32 left_joystick_y

uint8 gear_switching
uint8 pause_button
uint8 left_custom_button
uint8 right_custom_button

float32 thumb_wheel
uint8 trigger

float32 mouse_x_axis
float32 mouse_y_axis
float32 mouse_wheel

uint8 mouse_lb
uint8 mouse_rb
uint8 mouse_mb

uint8 key_w
uint8 key_s
uint8 key_a
uint8 key_d
uint8 key_shift
uint8 key_ctrl
uint8 key_q
uint8 key_e
uint8 key_r
uint8 key_f
uint8 key_g
uint8 key_z
uint8 key_x
uint8 key_c
uint8 key_v
uint8 key_b 