std_msgs/Header header
uint8 online

float32 left_x
float32 left_y
float32 right_x
float32 right_y
float32 dial

uint8 gear_switching
uint8 pause_button
uint8 left_custom_button
uint8 right_custom_button
uint8 trigger_button

uint8 w
uint8 s
uint8 a
uint8 d
uint8 q
uint8 e
uint8 r
uint8 f
uint8 g
uint8 z
uint8 x
uint8 c
uint8 v
uint8 b
uint8 shift
uint8 ctrl

int16 mouse_x
int16 mouse_y
int16 mouse_z
uint8 mouse_left_clicked
uint8 mouse_mid_clicked
uint8 mouse_right_clicked